### ISSUE TITLE
Issue with self and np.array

### ISSUE THREAD

**Issue by wolfv** [cosmo-ethz/hope#49]
When adding an np array to the test class and trying to access said array from a jitted function, it crashes while generating the CPP:

```
Traceback (most recent call last):
  File "examples/hope_class.py", line 56, in <module>
    example()
  File "examples/hope_class.py", line 47, in example
    r = dc.run(2)
  File "/home/wolfv/Programs/hope/hope/_wrapper.py", line 71, in _hope_callback
    return self(*args) if self.cache is None else self.cache(*args)
  File "/home/wolfv/Programs/hope/hope/_wrapper.py", line 77, in __call__
    ASTTransformer(self.modtoken).module_visit(self.fkt, args)
  File "/home/wolfv/Programs/hope/hope/_transformer.py", line 706, in module_visit
    parsed = self.visit(fktast)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/home/wolfv/Programs/hope/hope/_transformer.py", line 644, in visit_FunctionDef
    AllocateVisitor(self.variables).visit(self.token.body)
  File "/home/wolfv/Programs/hope/hope/_ast.py", line 387, in visit
    return getattr(self, 'visit_{0}'.format(type(node).__name__))(node)
  File "/home/wolfv/Programs/hope/hope/_transformer.py", line 152, in visit_Body
    start = check_blocks(start)
  File "/home/wolfv/Programs/hope/hope/_transformer.py", line 141, in check_blocks
    if self.variables[symbol].scope == "block":
KeyError: u'self.c'
```

Source:

```python
# Copyright (C) 2014 ETH Zurich, Institute for Astronomy

'''
A simple example to demonstrate the supported functionality with class methods.

Note: this should be used with precaution as unboxing member variables causes some overhead

Created on Oct 23, 2014

author: jakeret
'''
from __future__ import print_function, division, absolute_import, unicode_literals

import os
import shutil
import hope

import numpy as np
prefix = "hope_class"

hope.config.keeptemp = True
hope.config.verbose = True
hope.config.prefix = prefix

if os.path.exists(prefix):
    shutil.rmtree(prefix)

@hope.jit
def external(a, b):
    return a + b

class DemoClass(object):
    def __init__(self):
        self.a = 1
        self.c = np.array([1, 2, 3])
        
    @hope.jit
    def run(self, b):
        return self.a + b + self.c

    def run_external(self, b):
        return external(self.a, b)


def example():
    dc = DemoClass()
    #jit compile a method of a class
    r = dc.run(2)
    assert r == 3

    #call jitted function from a class
    r = dc.run_external(2)
    assert r == 3
    
if __name__ == '__main__':
    example()
```

**Comment by wolfv** [comment]
My best guess is that the problem is somewhere in the symbolcollector, and this line?

`if isinstance(node.variable, ObjectAttr): return [".".join(trace)]`

**Comment by cosmo-ethz** [comment]
There seems indeed to be an issue in the `SymbolNamesCollector`. I just pushed a new branch that fixes the problem. The thing is, that at the moment I can't remember why I originally implemented the check. :-/

**Comment by cosmo-ethz** [comment]
Merged the branch already a while ago
